spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/elane
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9011
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka