spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/elane
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver